spring:
  profiles:
    active: local

welcome:
  message: Start springboot-vuejs Sample Application
server:
  port: 9001

---
spring:
  profiles: local
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    #prefix: file:src/main/resources/templates/
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      period: 0

zuul:
  ignoredServices: '*'
  routes:
    nodejs:
      path: /js/**
      url: http://localhost:9000/js

nodejs:
  proxy: enabled